const themes = [
  {
    theme: 'HEART',
  },
  {
    theme: 'CAT',
  },
  {
    theme: 'PIZZA',
  },
  {
    theme: 'SNAKE',
  },
  {
    theme: 'RAINBOW',
  },
  {
    theme: 'STRAWBERRY',
  },
  {
    theme: 'SKULL',
  },
  {
    theme: 'POTION',
  },
  {
    theme: 'VAMPIRE',
  },
  {
    theme: 'SWORD',
  },
  {
    theme: 'MOON',
  },
  {
    theme: 'GHOST',
  },
  {
    theme: 'MONEY',
  },
  {
    theme: 'BUNNY',
  },
  {
    theme: 'ROSE',
  },
  {
    theme: 'ALIEN',
  },
  {
    theme: 'MUSHROOM',
  },
  {
    theme: 'SMILE',
  },
  {
    theme: 'DOG',
  },
];

const grid = [
  { minigrid: '#fff' },
  { minigrid: '#fff' },
  { minigrid: '#fff' },
  { minigrid: '#fff' },
  { minigrid: '#fff' },
  { minigrid: '#fff' },
  { minigrid: '#fff' },
  { minigrid: '#fff' },
  { minigrid: '#fff' },
  { minigrid: '#fff' },
  { minigrid: '#fff' },
  { minigrid: '#fff' },
  { minigrid: '#fff' },
  { minigrid: '#fff' },
  { minigrid: '#fff' },
  { minigrid: '#fff' },
  { minigrid: '#fff' },
  { minigrid: '#fff' },
  { minigrid: '#fff' },
  { minigrid: '#fff' },
  { minigrid: '#fff' },
  { minigrid: '#fff' },
  { minigrid: '#fff' },
  { minigrid: '#fff' },
  { minigrid: '#fff' },
  { minigrid: '#fff' },
  { minigrid: '#fff' },
  { minigrid: '#fff' },
  { minigrid: '#fff' },
  { minigrid: '#fff' },
  { minigrid: '#fff' },
  { minigrid: '#fff' },
  { minigrid: '#fff' },
  { minigrid: '#fff' },
  { minigrid: '#fff' },
  { minigrid: '#fff' },
  { minigrid: '#fff' },
  { minigrid: '#fff' },
  { minigrid: '#fff' },
  { minigrid: '#fff' },
  { minigrid: '#fff' },
  { minigrid: '#fff' },
  { minigrid: '#fff' },
  { minigrid: '#fff' },
  { minigrid: '#fff' },
  { minigrid: '#fff' },
  { minigrid: '#fff' },
  { minigrid: '#fff' },
  { minigrid: '#fff' },
  { minigrid: '#fff' },
  { minigrid: '#fff' },
  { minigrid: '#fff' },
  { minigrid: '#fff' },
  { minigrid: '#fff' },
  { minigrid: '#fff' },
  { minigrid: '#fff' },
  { minigrid: '#fff' },
  { minigrid: '#fff' },
  { minigrid: '#fff' },
  { minigrid: '#fff' },
  { minigrid: '#fff' },
  { minigrid: '#fff' },
  { minigrid: '#fff' },
  { minigrid: '#fff' },
  { minigrid: '#fff' },
  { minigrid: '#fff' },
  { minigrid: '#fff' },
  { minigrid: '#fff' },
  { minigrid: '#fff' },
  { minigrid: '#fff' },
  { minigrid: '#fff' },
  { minigrid: '#fff' },
  { minigrid: '#fff' },
  { minigrid: '#fff' },
  { minigrid: '#fff' },
  { minigrid: '#fff' },
  { minigrid: '#fff' },
  { minigrid: '#fff' },
  { minigrid: '#fff' },
  { minigrid: '#fff' },
  { minigrid: '#fff' },
  { minigrid: '#fff' },
  { minigrid: '#fff' },
  { minigrid: '#fff' },
  { minigrid: '#fff' },
  { minigrid: '#fff' },
  { minigrid: '#fff' },
  { minigrid: '#fff' },
  { minigrid: '#fff' },
  { minigrid: '#fff' },
  { minigrid: '#fff' },
  { minigrid: '#fff' },
  { minigrid: '#fff' },
  { minigrid: '#fff' },
  { minigrid: '#fff' },
  { minigrid: '#fff' },
  { minigrid: '#fff' },
  { minigrid: '#fff' },
  { minigrid: '#fff' },
  { minigrid: '#fff' },
];
const palette = [
  { color: '#E6E7E7' },
  { color: '#31373D' },
  { color: '#C1694F' },
  { color: '#55B1ED' },
  { color: '#78B159' },
  { color: '#A98ED6' },
  { color: '#DE2E44' },
  { color: '#FACB58' },
  { imageURl: '../assets/color_palette_erase.png' },
];
export default { themes, grid, palette };
